name: Main

on:
  push:
    branches: "main"
  pull_request:
    branches: "*"

jobs:
  brew:
    name: Brew (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - "macos-14"
          - "macos-13"
          - "macos-12"

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Install tap
        run: brew tap --verbose ${{ github.repository }} .

      - name: Install Go
        run: brew install --overwrite go

      - name: Install Geneve
        run: brew install --verbose geneve

      - name: Try Geneve
        run: |
          geneve version
          if [ $(geneve version | grep "version:" | head -2 | sort | uniq | wc -l) -ne 1 ]; then \
            echo -e "\nApplication and module versions do not match"; \
            false; \
          fi
